### ISSUE TITLE
MRC component中的MRC Examples不对

### ISSUE THREAD

**Issue by raullese** [baidubce/app-builder#1]
class MRC(CompletionBaseComponent):
    """
    阅读理解问答组件，基于大模型进行阅读理解问答，支持拒答、澄清、重点强调、友好性提升、溯源等多种功能，可用于回答用户提出的问题。

    Examples:

        .. code-block:: python

            import appbuilder
            os.environ["APPBUILDER_TOKEN"] = '...'

            mrc_component = appbuilder.MRC()

            # 获取功能说明
            instructions = mrc_component.get_instruction_set()

            # 输出功能说明
            for key, value in instructions.items():
                print(f"{key}: {value}")

            # 模拟运行MRC组件，开启澄清和友好性提升功能
            result = mrc_component.run(appbuilder.Message("什么是人工智能？"), clarify=True, friendly=True)

            # 输出运行结果
            print(result)

**Comment by seiriosPlus** [comment]
fixed by #8
