### ISSUE TITLE
V0.4.0版本SDK在在Python 3.11版本上报错

### ISSUE THREAD

**Issue by deffe1** [baidubce/app-builder#148]
![image](https://github.com/baidubce/app-builder/assets/152057159/fe165a09-909f-48a5-b687-cfb11cba57e4)
升级V0.4.0版本SDK后，在Python 3.11版本上报错，导入包出问题。

**Comment by ide-rea** [comment]
在Linux容器中，使用相同版本的Python==3.11.5, Ipython==8.15.0，没有复现出类似问题

<img width="611" alt="image" src="https://github.com/baidubce/app-builder/assets/30512600/e4a6443b-8aa9-4a5b-817b-fa1a50ebfb7d">

**Comment by deffe1** [comment]
问题已解决，感谢支持
