### ISSUE TITLE
SDK目前不支持导入结构化文件，是否可以开发该功能

### ISSUE THREAD

**Issue by yiligi** [baidubce/app-builder#252]
目前版本SDK导入Excel模板文档会将其当作普通文档进行处理，从AppBuilder控制台上传就是正常的处理方式，请问什么时候可以支持该功能

**Comment by guru4elephant** [comment]
我们会尽快开放这个功能 @yiligi

**Comment by MrChengmo** [comment]
> 目前版本SDK导入Excel模板文档会将其当作普通文档进行处理，从AppBuilder控制台上传就是正常的处理方式，请问什么时候可以支持该功能

该功能在最新的 0.9.0已支持
