### ISSUE TITLE
query改写效果异常

### ISSUE THREAD

**Issue by guru4elephant** [baidubce/app-builder#30]
为什么appbuilder sdk 的query改写不是对最后的query进行改写，而是直接回答了。
![27F120F0C6E85524AFFF25A42FA5BDBF](https://github.com/baidubce/app-builder/assets/35550832/beaea3a1-ae8d-4b90-93b7-6722bb5d6183)

**Comment by LeeJodie** [comment]
![2f8faa043ef2d5b48dd7ab61b4f35efb](https://github.com/baidubce/app-builder/assets/19773473/eab22939-1f1c-417d-9895-fd60e985d1c1)

抱歉，这个默认模型需要修改为model="eb-turbo-appbuilder"

**Comment by LeeJodie** [comment]
> 为什么appbuilder sdk 的query改写不是对最后的query进行改写，而是直接回答了。 ![27F120F0C6E85524AFFF25A42FA5BDBF](https://private-user-images.githubusercontent.com/35550832/293310891-beaea3a1-ae8d-4b90-93b7-6722bb5d6183.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxNjU0MTYsIm5iZiI6MTcwNDE2NTExNiwicGF0aCI6Ii8zNTU1MDgzMi8yOTMzMTA4OTEtYmVhZWEzYTEtYWU4ZC00YjkwLTkzYjctNjcyMmJiNWQ2MTgzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDAzMTE1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZjM1ODgxZGMzOWFiNjg4ZDAwNTJmMmI3MDRiMDMzMTJmMDcyMWQ3NDBlNzFjYzliYjQ3ZDNiMGFiOWZkYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rJdOQKqKHXNHk4dGypH3tXkwkrtvLV67pqz-2eXG3gA)

![2f8faa043ef2d5b48dd7ab61b4f35efb](https://github.com/baidubce/app-builder/assets/19773473/34ac9e23-103a-4862-8141-42149ea8787e)

抱歉，这个默认模型需要修改为model="eb-turbo-appbuilder"
