### ISSUE TITLE
这写的啥啊top p完全反了。。。改了吧

### ISSUE THREAD

**Issue by aiyinyuedejustin** [baidubce/app-builder#414]
https://github.com/baidubce/app-builder/blob/fa905b59c89ecbc046427f68e66e0f029595b289/appbuilder/core/assistant/type/public_type.py#L126

<img width="1226" alt="image" src="https://github.com/user-attachments/assets/47bf9db2-f092-4c38-a4b7-9ab6a31e1896">

谁写的这doc string。 

另外https://cloud.baidu.com/doc/AppBuilder/s/nluzkdben    这个文档的top p也写反了

**Comment by userpj** [comment]
收到

**Comment by userpj** [comment]
https://github.com/baidubce/app-builder/pull/418
