### ISSUE TITLE
不支持pyinstaller打包

### ISSUE THREAD

**Issue by wangtu** [baidubce/app-builder#423]
使用打包pyinstaller死活打不进去appbuilder

**Comment by MrChengmo** [comment]
具体报错是什么？我们复现下看看

**Comment by wangtu** [comment]
> 具体报错是什么？我们复现下看看

1、pycharm工具开发、运行、调试都OK，于是计划采用pyinstaller打包exe程序
2、exe启动后发现运行到指定行 import appbuilder 会闪退。注释改行重新打包则恢复
3、尝试使用过 pyinstaller.exe  --hidden-import=appbuilder-sdk 手工导入依赖，再次打包，效果同2也闪退

因此是否是appbuilder大家都是开发服务端，没人适配过pyinstaller的本地exe程序吗？望大佬能指导下

**Comment by C9luster** [comment]
本地使用pyinstaller打包py文件，并运行生成的test文件【因为为mac系统，因此不是exe文件】，没有出现import appbuilder的报错，使用日志记录运行流程也没有出现相关报错

**Comment by C9luster** [comment]
本地使用pyinstaller打包py文件，并运行生成的test文件【因为为mac系统，因此不是exe文件】，没有出现import appbuilder的报错，使用日志记录运行流程也没有出现相关报错

**Comment by C9luster** [comment]
本地使用pyinstaller打包py文件，并运行生成的test文件【因为为mac系统，因此不是exe文件】，没有出现import appbuilder的报错，使用日志记录运行流程也没有出现相关报错
（1）麻烦查看pip install appbuilder-sdk是否是在python3环境下安装的，是否存在环境问题
【包名与模块名不同本身并不会直接导致 PyInstaller 打包时导入失败。导入失败的原因可能更多地与模块的安装、路径设置或循环导入等问题有关。因此，在使用 PyInstaller 打包 Python 程序时，应确保所有依赖都已正确配置，并检查是否有其他潜在的导入问题】

**Comment by C9luster** [comment]
是否适配适配过pyinstaller的本地exe程序我之后测试一下

**Comment by MrChengmo** [comment]
最终解决方法为pyinstall 打包要禁用upx， 使用appbuilder则需要禁用，否则有影响。--noupx
