### ISSUE TITLE
知识库-上传文档-选择”整文件切片“

### ISSUE THREAD

**Issue by xueyayang** [baidubce/app-builder#443]
![image](https://github.com/user-attachments/assets/0c5f4473-0d3f-44a6-926f-5c4b9e6df631)

代码实现上述选项，应该传哪个值？

查看以了以下代码，没有找到头绪：
```
class CustomProcessRule(BaseModel):
    separators: list[str] = Field(..., description="分段符号列表", example=[",", "?"])
    target_length: int = Field(..., description="分段最大长度", ge=300, le=1200)
    overlap_rate: float = Field(
        ..., description="分段重叠最大字数占比，推荐值0.25", ge=0, le=0.3, example=0.2
    )
    
class DocumentChunker(BaseModel):
choices: list[str] = Field(..., description="选择项")   # 这里有个枚举值吗？
prependInfo: list[str] = Field(
    ...,
    description="chunker关联元数据，可选值为title (增加标题), filename(增加文件名)",
)
separator: Optional[DocumentSeparator] = Field(..., description="分段符号")
pattern: Optional[DocumentPattern] = Field(None, description="正则表达式")
```

**Comment by userpj** [comment]
参考使用文档：https://github.com/baidubce/app-builder/blob/master/docs/basic_module/knowledgebase.md

**Comment by xueyayang** [comment]
> 参考使用文档：https://github.com/baidubce/app-builder/blob/master/docs/basic_module/knowledgebase.md 7、导入知识库。 DocumentChunker类下的choices变量，["onePage"]为整文件切片。

thx a lot. I will try later, then close this issue.

**Comment by xueyayang** [comment]
可以了。按照文档选 onePage 可以上传。此问题已解决。

另外一个小问题，separator 参数是必须的，但文档里写是 Optional.

>  File "C:\Python312\Lib\site-packages\pydantic\main.py", line 171, in __init__
>     self.__pydantic_validator__.validate_python(data, self_instance=self)
> pydantic_core._pydantic_core.ValidationError: 1 validation error for DocumentChunker
> separator   >>>>>>>>>>>>>>>>> 这里显示错误
>   Field required [type=missing, input_value={'choices': ['onePage'], 'prependInfo': []}, input_type=dict]
>     For further information visit https://errors.pydantic.dev/2.6/v/missing

```
class DocumentChunker(BaseModel):
    choices: list[str] = Field(..., description="使用哪些chunker方法 (separator | pattern | onePage), separator：自定义切片—标识符，pattern：自定义切片—标识符中选择正则表达式，onePage：整文件切片")
    prependInfo: list[str] = Field(
        ...,
        description="chunker关联元数据，可选值为title (增加标题), filename(增加文件名)",
    )
    separator: Optional[DocumentSeparator] = Field(..., description="分段符号")   # 这里显示是Optional
    pattern: Optional[DocumentPattern] = Field(None, description="正则表达式")
```
