### ISSUE TITLE
pytest抛出警告PydanticDeprecatedSince20

### ISSUE THREAD

**Issue by amchii** [baidubce/app-builder#541]
单元测试时pytest抛出pydantic的弃用警告：

PydanticDeprecatedSince20: `pydantic.config.Extra` is deprecated, use literal values instead (e.g. `extra='allow'`). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
    class Message(BaseModel, Generic[_T], extra=Extra.allow):

**Comment by MrChengmo** [comment]
收到

**Comment by MrChengmo** [comment]
已更改deprecated的pydantic使用方式：https://github.com/baidubce/app-builder/pull/565
