### ISSUE TITLE
readme中存在错误代码

### ISSUE THREAD

**Issue by ylembot1** [baidubce/app-builder#72]
<img width="853" alt="image" src="https://github.com/baidubce/app-builder/assets/71958062/2c964c0d-0b99-4254-a415-2f418e9958e4">

**Comment by ylembot1** [comment]
建议修复readme中的小错误，减少用户使用成本

**Comment by guru4elephant** [comment]
我们快速修复

**Comment by seiriosPlus** [comment]
fixed by #107
